### ISSUE TITLE
How small could this firmware go?

### ISSUE THREAD

**Issue by mithro** [mmoskal/uf2-stm32f#1]
I was wondering how small you could make a UF2 compatible firmware? Could you fit it into a M0+ class device? Could you combined it with something like @xobs' https://github.com/xobs/grainuum stack?

**Comment by xobs** [comment]
I have an example of Grainuum running on an M0+ bootloader at https://github.com/xobs/joyboot however it's using HID and not U2F.  If I were to redo `joyboot` (to actually produce the boards) I would use U2F now.

**Comment by mithro** [comment]
By that I assume you mean DFU rather than U2F?

**Comment by mithro** [comment]
Or UF2?

**Comment by xobs** [comment]
...yes, sorry.  I hadn't heard of UF2 before, but I suppose the `joyboot` firmware could be easily adapted to UF2.

**Comment by mmoskal** [comment]
sorry for late reply, here's one for STM32F1 (which is M3, but small) https://github.com/mmoskal/uf2-stm32f103; here's one for SAMD21 (which is M0+) https://github.com/Microsoft/uf2-samdx1

I even had it running on the atmega usb interface chip of uno.

For full list see here https://github.com/Microsoft/uf2#bootloaders
