### ISSUE TITLE
about the ILI9341 parallel 8bit screen

### ISSUE THREAD

**Issue by wbbw55** [mmoskal/uf2-stm32f#13]
Hi~~~I tested f412 with the big screen but no any display, because there is no 8-bit parallel screen driver for ILI9341(320x240).

**Comment by mmoskal** [comment]
Correct, it's not implemented yet. PRs are welcome!

**Comment by wbbw55** [comment]
ok I already do some code, the pr will post after some test done.;)

**Comment by wbbw55** [comment]
Hi, I forked the project and added driver code for ili9341 parallel 8bit screen:
https://github.com/wbbw55/uf2-stm32f-ili9341p8

**Comment by mmoskal** [comment]
looks good, PRs are welcome!
