### ISSUE TITLE
missing file "libopencm3/stm32/f4/nvic.h"

### ISSUE THREAD

**Issue by shaoziyang** [mmoskal/uf2-stm32f#3]
When I compile the source, it prompt 

> In file included from libopencm3/include/libopencm3/cm3/nvic.h:133:0,
>                  from usb.c:42:
> libopencm3/include/libopencm3/dispatch/nvic.h:14:11: fatal error: libopencm3/stm32/f4/nvic.h: No such file or directory

**Comment by mmoskal** [comment]
I think we now compile libopencm3 automatically, so this should be resovled
